// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package data

import (
	"context"

	"github.com/kyren223/eko/pkg/snowflake"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  id, content, sender_id, frequency_id, receiver_id
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, sender_id, content, edited, frequency_id, receiver_id
`

type CreateMessageParams struct {
	ID          snowflake.ID
	Content     string
	SenderID    snowflake.ID
	FrequencyID *snowflake.ID
	ReceiverID  *snowflake.ID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.Content,
		arg.SenderID,
		arg.FrequencyID,
		arg.ReceiverID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.Content,
		&i.Edited,
		&i.FrequencyID,
		&i.ReceiverID,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, sender_id, content, edited, frequency_id, receiver_id FROM messages
ORDER BY id
`

func (q *Queries) ListMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Content,
			&i.Edited,
			&i.FrequencyID,
			&i.ReceiverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
