// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"crypto/ed25519"
	"github.com/kyren223/eko/pkg/snowflake"
)

type Frequency struct {
	ID        snowflake.ID
	NetworkID snowflake.ID
	Name      string
	HexColor  *string
	Perms     int64
	Position  int64
}

type Message struct {
	ID          snowflake.ID
	SenderID    snowflake.ID
	Content     string
	Edited      bool
	FrequencyID *snowflake.ID
	ReceiverID  *snowflake.ID
}

type Network struct {
	ID         snowflake.ID
	OwnerID    snowflake.ID
	Name       string
	Icon       string
	BgHexColor *string
	FgHexColor string
	IsPublic   bool
}

type NetworkBannedUser struct {
	NetworkID    snowflake.ID
	BannedUserID snowflake.ID
	BannedAt     string
	Reason       *string
}

type User struct {
	ID          snowflake.ID
	Name        string
	PublicKey   ed25519.PublicKey
	Description *string
	IsPublicDm  bool
	IsDeleted   bool
}

type UserBlockedUser struct {
	BlockerUserID snowflake.ID
	BlockedUserID snowflake.ID
}

type UserTrustedUser struct {
	TrusterUserID    snowflake.ID
	TrustedUserID    snowflake.ID
	TrustedPublicKey []byte
}

type UsersNetwork struct {
	UserID    snowflake.ID
	NetworkID snowflake.ID
	JoinedAt  string
	IsAdmin   bool
	IsMuted   bool
}
