// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"crypto/ed25519"
	"github.com/kyren223/eko/pkg/snowflake"
)

type BlockedUser struct {
	BlockingUserID snowflake.ID
	BlockedUserID  snowflake.ID
}

type Frequency struct {
	ID        snowflake.ID
	NetworkID snowflake.ID
	Name      string
	HexColor  string
	Perms     int64
	Position  int64
}

type Member struct {
	UserID    snowflake.ID
	NetworkID snowflake.ID
	JoinedAt  string
	IsMember  bool
	IsAdmin   bool
	IsMuted   bool
	IsBanned  bool
	BanReason *string
}

type Message struct {
	ID          snowflake.ID
	SenderID    snowflake.ID
	Content     string
	Edited      bool
	FrequencyID *snowflake.ID
	ReceiverID  *snowflake.ID
}

type Network struct {
	ID         snowflake.ID
	OwnerID    snowflake.ID
	Name       string
	Icon       string
	BgHexColor string
	FgHexColor string
	IsPublic   bool
}

type TrustedUser struct {
	TrustingUserID   snowflake.ID
	TrustedUserID    snowflake.ID
	TrustedPublicKey ed25519.PublicKey
}

type User struct {
	ID          snowflake.ID
	Name        string
	PublicKey   ed25519.PublicKey
	Description string
	IsPublicDM  bool
	IsDeleted   bool
}

type UserData struct {
	UserID snowflake.ID
	Data   string
}
