// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"crypto/ed25519"
	"github.com/kyren223/eko/pkg/snowflake"
)

type Frequency struct {
	ID        snowflake.ID
	NetworkID snowflake.ID
	Name      string
}

type Message struct {
	ID          snowflake.ID
	SenderID    snowflake.ID
	Content     string
	FrequencyID *snowflake.ID
	ReceiverID  *snowflake.ID
}

type Network struct {
	ID      snowflake.ID
	Name    string
	OwnerID snowflake.ID
}

type User struct {
	ID        snowflake.ID
	Name      string
	PublicKey ed25519.PublicKey
}

type UsersNetwork struct {
	UserID    snowflake.ID
	NetworkID snowflake.ID
}
