name: continious deployment

on:
  push:
    branches: [master]

jobs:
  cd:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Runs CI (will checkout the repo)
        uses: ./.github/workflows/ci.yml

      - name: Build executable
        run: GOOS=linux GOARCH=amd64 go build ./cmd/server -o ./eko-server

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz"
          SOURCE: "eko-server"
          REMOTE_HOST: eko.kyren.codes
          REMOTE_USER: website
          TARGET: "/srv/website"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT

