name: Build Go binaries on github release

on:
  release:
    types: [created]  # only runs when you manually click "Create release" matching a tag

permissions:
  contents: write
  packages: write

jobs:
  publish-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [386, amd64, arm64]
        exclude:
          - goarch: "386"  # darwin/386 not supported
            goos: darwin
          - goarch: arm64  # windows/arm64 well supported now, but you can exclude if you like
            goos: darwin
    steps:
      - uses: actions/checkout@v4

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.EKO_RELEASE_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: eko
          project_path: ./cmd/client
          sha256sum: true
          md5sum: false
          overwrite: true
          retry: 5
